source = ""
words_source_RIMES = "../../Data/RIMES/RIMES/Images"
words_transcription_RIMES = "../../Data/RIMES/RIMES/Transcriptions"
best_model = "runs/detect/best_train/weights/best.pt"
padding_noB = "runs/detect/train_padding_noB/weights/best.pt"
rect_B = "runs/detect/train_rect_B/weights/best.pt"
rect_noB = "runs/detect/train_rect_noB/weights/best.pt"
