source = ""
words_source_RIMES = "../../Data/RIMES/RIMES/Images/eval"
words_transcription_RIMES = "../../Data/RIMES/RIMES/Transcriptions/eval"
words_source_phcd = "../../Data/phcd/Images"
words_source_Rodrigo = "../../Data/Rodrigo/Images"
words_source_VNOnDB = "../../Data/VNonDB/Images"
